service: serverless-invoke-local-bug-1 # NOTE: update this with your service name

custom:
  global:
    bucketName:
      Fn::Join:
      - ''
      - - 'test-'
        - '1b4d7ccd-ce10-4b97-b2d4-ffa978e40464'


provider:
  name: aws
  runtime: java8

  # you can overwrite defaults here
  stage: dev
  region: ca-central-1

  # you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
  - Effect: "Allow"
    Action:
    - "s3:*"
    - "s3:PutObject"
    - "s3:DeleteObject"
    - "s3:GetObjectTagging"
    - "s3:PutObjectTagging"
    - "s3:PutBucketNotification"
    Resource: "arn:aws:s3:::test-1b4d7ccd-ce10-4b97-b2d4-ffa978e40464"


# you can add packaging information here
package:
  artifact: target/serverless-invoke-local-bug-dev.jar

functions:
  hello:
    handler: com.serverless.Handler
    events:
    - existingS3:
        # Known bug, we are hardcoding the trigger for now: https://github.com/matt-filion/serverless-external-s3-event/issues/66
        # bucket: ${self:custom.global.bucketName}
        bucket: "test-1b4d7ccd-ce10-4b97-b2d4-ffa978e40464"
        events:
        - s3:ObjectCreated:*
        rules:
        - prefix: export/


resources:
  Resources:
    BucketName:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.global.bucketName}


plugins:
  - serverless-plugin-existing-s3
  - serverless-pseudo-parameters

